/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MalliCode;


import TableModel.ProjectTableModel;
import TableModel.TeamMemberModel;
import java.util.List;
import one.CardLayouts;
import one.ProjectQueryGUI;
import ooad.*;
import ooad.Project;
import ooad.TeamMember;

/**
 *
 * @author Mallika
 */
public class Search extends javax.swing.JPanel {

    public ProjectTableModel projectTableModel;
    public TeamMemberModel teamMemberModel;
    public String proj_name;
    public CardLayouts card;
    public ProjectQueryGUI pro;
    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        addItems();
        proj_name = null;
        //card = new CardLayouts();
        
    }
    
    public void addItems(){
        projectTableModel=new ProjectTableModel();
        teamMemberModel=new TeamMemberModel();
        List<Project> projectResultList=projectTableModel.getList();
        List<TeamMember> teamMemberResultList=teamMemberModel.getList();
        
        for(int i=0;i<projectResultList.size();i++){
            projectNameJComboBox.addItem(projectResultList.get(i).getProjectName());
        }
        
        for(int i=0;i<teamMemberResultList.size();i++){
            teamMemberJComboBox.addItem(teamMemberResultList.get(i).getMemberName());
        }
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectName = new javax.swing.JLabel();
        TeamMemberName = new javax.swing.JLabel();
        projectNameJComboBox = new javax.swing.JComboBox();
        teamMemberJComboBox = new javax.swing.JComboBox();
        searchByProjectName = new javax.swing.JButton();
        searchByTeamMember = new javax.swing.JButton();

        projectName.setText("Project Name :");

        TeamMemberName.setText("Team Members :");

        projectNameJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Project>" }));

        teamMemberJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Team Member>" }));

        searchByProjectName.setText("Search Project Name");
        searchByProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByProjectNameActionPerformed(evt);
            }
        });

        searchByTeamMember.setText("Search Team Member");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TeamMemberName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teamMemberJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectName)
                        .addGap(43, 43, 43)
                        .addComponent(projectNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchByProjectName)
                    .addComponent(searchByTeamMember))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectName)
                    .addComponent(projectNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByProjectName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeamMemberName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teamMemberJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchByTeamMember)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void searchByProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByProjectNameActionPerformed
        // TODO add your handling code here:
        proj_name = projectNameJComboBox.getSelectedItem().toString();
        pro = new ProjectQueryGUI(proj_name);
        
        this.add(pro);
        this.setVisible(true);
        //card.showProjDetails();
        
        
    }//GEN-LAST:event_searchByProjectNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TeamMemberName;
    private javax.swing.JLabel projectName;
    private javax.swing.JComboBox projectNameJComboBox;
    private javax.swing.JButton searchByProjectName;
    private javax.swing.JButton searchByTeamMember;
    private javax.swing.JComboBox teamMemberJComboBox;
    // End of variables declaration//GEN-END:variables
}
