/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MalliCode;


import ooad.Project;
import ooad.Task;
import ooad.TeamMember;
import TableModel.ProjectTableModel;
import NewCode.TaskModel;
import TableModel.TeamMemberModel;
import TableModel.UserModel;
import java.text.ParseException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mallika
 */
public class TeamMemberTask extends javax.swing.JPanel {

    private static final String PERSISTENCE_UNIT_NAME = "OOADPU";  // Used in persistence.xml
    private static EntityManagerFactory factory;  // JPA  
    private EntityManager manager;
    private EntityTransaction transaction;
    
     public TeamMemberModel teamMemberModel;
     public TaskModel taskModel;
     public List<TeamMember> memberResultList;
     public List<Task> taskResultList;
     public DefaultTableModel model;
    
    /**
     * Creates new form TeamMemberTask
     */
    public TeamMemberTask() {
        initComponents();
          teamMemberModel=new TeamMemberModel();
        memberResultList=teamMemberModel.getList();
        taskModel=new TaskModel();
        taskResultList=taskModel.getList();
    readTeamMemberTaskTableContents();
    addItems();
    }
    
    public void addItems(){
      
        
        for(int i=0;i<memberResultList.size();i++){
            
            teamComboBox.addItem(memberResultList.get(i).getMemberName());
        }
        
        
        
       
        
    }

    public void readTeamMemberTaskTableContents() {
        model=(DefaultTableModel) jTable1.getModel();
        
        factory = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME);
        manager = factory.createEntityManager();
        transaction=manager.getTransaction();

        transaction.begin();
//        Query query = manager.createQuery("SELECT distinct u.userName, u.password, p.projectName, p.status from project p INNER join p.user u");
        Query query=manager.createQuery("SELECT t FROM task t JOIN t.memberId m");
        List<Task> result = query.getResultList();
        
        for (int i=0;i<result.size();i++) {
//            MyClass mobj = MyClass.class.cast(obj);
            System.out.println(result.get(i).getTask());
            model.addRow(new Object[]{result.get(i).getMemberId().getMemberName(),result.get(i).getTask(),result.get(i).getDeadline(), result.get(i).getDependency()});
        }
        
        

        
        transaction.commit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        teamComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        taskTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dependencyTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team Member", "Task", "Deadline", "Dependency"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(jTable1);

        teamComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select member>" }));
        teamComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Team member");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Task :");
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 18));

        taskTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        taskTextField.setPreferredSize(new java.awt.Dimension(114, 22));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Dependency :");
        jLabel3.setPreferredSize(new java.awt.Dimension(88, 18));

        dependencyTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        dependencyTextField.setPreferredSize(new java.awt.Dimension(114, 22));
        dependencyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dependencyTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Date (YYYY-MM-DD) :");
        jLabel4.setPreferredSize(new java.awt.Dimension(38, 18));

        dateTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        dateTextField.setPreferredSize(new java.awt.Dimension(114, 22));
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        addButton.setText("Add");
        addButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        addButton.setPreferredSize(new java.awt.Dimension(27, 21));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dependencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 228, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(teamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(taskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dependencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dependencyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dependencyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dependencyTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        Object[] array = new Object[6];
        array[0] = 3;
        array[1]= taskTextField.getText();
        array[2]= 101;
        array[3]= dateTextField.getText();
        array[4]= dependencyTextField.getText();
//        array[5] = 100;
        
        //to get member ID :
         for(int i =0;i<memberResultList.size();i++){
            if((teamComboBox.getSelectedItem().toString()).equals(memberResultList.get(i).getMemberName()))
                array[5]=memberResultList.get(i).getMemberId();
         }
        
            
            
        System.out.println(Arrays.toString(array));
        
            
            taskModel.addRow(array);
            
            
            model.addRow(new Object[]{teamComboBox.getSelectedItem().toString(),array[1],array[3], array[4]});
        
//         updateJoinTable();
        
    }//GEN-LAST:event_addButtonActionPerformed

//    public void updateJoinTable(){
//        factory = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME);
//        manager = factory.createEntityManager();
//        transaction=manager.getTransaction();
//
//        transaction.begin();
//        Query query = manager.createQuery("SELECT distinct u.userName, u.password, p.projectName, p.status from project p INNER join p.user u");
//        Query query=manager.createQuery("SELECT t FROM task t JOIN t.memberId m where t.taskId=3");
//        List<Task> result = query.getResultList();
//        
//        
//        model.addRow(new Object[]{result.get(0).getMemberId().getMemberName(),result.get(0).getTask(),result.get(0).getDeadline(), result.get(0).getDependency()});
//        
//        transaction.commit();
//    }
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
        int id = 0;
        for(int i =0;i<taskResultList.size();i++){
            if((jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString()).equals(taskResultList.get(i).getTask()))
                id=taskResultList.get(i).getTaskId();
         }
        
            taskModel.deleteRow(id);
            model.removeRow(jTable1.getSelectedRow());
            taskTextField.setText(" ");
            dependencyTextField.setText(" ");
            dateTextField.setText(" ");
            
//            updateJoinTable();
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dependencyTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField taskTextField;
    private javax.swing.JComboBox teamComboBox;
    // End of variables declaration//GEN-END:variables
}
