package one;
import MalliCode.Search;
import TableModel.ProjectTableModel;
import TableModel.TeamMemberModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.table.DefaultTableModel;
import ooad.*;
import ooad.Project;
import ooad.Project;
import ooad.TeamMember;
import ooad.TeamMember;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jas
 */
public class ProjectQueryGUI extends javax.swing.JPanel {

    /**
     * Creates new form ProjectQueryGUI
     */
    public ProjectTableModel projectTableModel;
   public TeamMemberModel teamMemberModel;
EntityManagerFactory emf;
       EntityManager manager;
//
        EntityTransaction transaction;
    
    public ProjectQueryGUI() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("OOADPU");
      manager = emf.createEntityManager();
//
 transaction = manager.getTransaction();
        addItems();
        
        
           
    }
    public void addItems(){
        projectTableModel=new ProjectTableModel();
        teamMemberModel=new TeamMemberModel();
        List<Project> projectResultList=projectTableModel.getList();
        List<TeamMember> teamMemberResultList=teamMemberModel.getList();
        
        for(int i=0;i<projectResultList.size();i++){
            projectNameJComboBox.addItem(projectResultList.get(i).getProjectName());
        } 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Statusp_stat = new javax.swing.JLabel();
        _status = new javax.swing.JTextField();
        p_budget = new javax.swing.JLabel();
        bud = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pro_tab = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        p_desc = new javax.swing.JTextArea();
        projectNameJComboBox = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        Statusp_stat.setBackground(new java.awt.Color(255, 255, 255));
        Statusp_stat.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Statusp_stat.setText("Status: ");

        _status.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        _status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _statusActionPerformed(evt);
            }
        });

        p_budget.setBackground(new java.awt.Color(255, 255, 255));
        p_budget.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        p_budget.setText("Overall Budget");

        bud.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        pro_tab.setFont(new java.awt.Font("Luminari", 3, 14)); // NOI18N
        pro_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team Members"
            }
        ));
        jScrollPane1.setViewportView(pro_tab);

        p_desc.setColumns(20);
        p_desc.setRows(5);
        p_desc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true), "Project Description", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Black", 0, 14))); // NOI18N
        p_desc.setSize(new java.awt.Dimension(50, 50));
        jScrollPane2.setViewportView(p_desc);

        projectNameJComboBox.setBackground(new java.awt.Color(255, 255, 255));
        projectNameJComboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        projectNameJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Project Name>" }));

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        edit.setText("Edit Project");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Statusp_stat)
                                .addGap(18, 18, 18)
                                .addComponent(_status, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(p_budget)
                                .addGap(26, 26, 26)
                                .addComponent(bud, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(projectNameJComboBox))
                    .addComponent(searchButton))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Statusp_stat)
                            .addComponent(_status, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_budget)
                            .addComponent(bud, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(edit)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void _statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__statusActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)pro_tab.getModel();
        deleteAllRows(model);
        String input = projectNameJComboBox.getSelectedItem().toString();
         
        ProjectTableModel pt = new ProjectTableModel();
 

        
        
        
        int id = 0;
        Project pro = null;
        transaction.begin();
        for (Iterator<Project> it = pt.projectResultList.iterator(); it.hasNext();) {
                  Project p = it.next();
                  if(p.getProjectName().equalsIgnoreCase(input)){
                      pro = p;
                      id = p.getUserId();
                  }
                      
              }
       
        
        TypedQuery<TeamMember> query = manager.createQuery("SELECT s FROM team_member s join s.userList u where u.userId = :unum",TeamMember.class); 
        query.setParameter("unum", id); 
        List<TeamMember> result = query.getResultList();
        
        for(TeamMember t : result){
            model.addRow(new Object[]{t.getMemberName()});
            System.out.println(t.getMemberName());
            
        }
         _status.setText(pro.getStatus());
        bud.setText(pro.getOverallBudget().toString());
        p_desc.setText(pro.getDescription());
        
        transaction.commit();
    }//GEN-LAST:event_searchButtonActionPerformed

    public static void deleteAllRows(final DefaultTableModel model) {
    for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
        model.removeRow(i);
    }
}
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String[] array = new String[4];
        
        array[0] = projectNameJComboBox.getSelectedItem().toString();
        array[1] = p_desc.getText();
        array[2] = _status.getText();
        array[3] = bud.getText();
        
        PreparedStatement st = null;
        Connection conn = null;
        ProjectTableModel pm;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ooad","root","jesus123"); 
            String query = "update  project set description = ?, overrall_budget= ?, status = ? where project_name = ?;";
            
            st = conn.prepareStatement(query);
            st.setString(1, array[1]);
            st.setFloat(2, Float.parseFloat(array[3]));
            st.setString(3, array[2]);
            st.setString(4, array[0]);
            st.execute();
            conn.setAutoCommit(false);
            conn.commit();
          st.close();
          conn.close();
          
      }
      catch (SQLException e) {
 
			System.out.println(e.getMessage());
            try {
                conn.rollback();
            } catch (SQLException ex) {
                Logger.getLogger(ProjectQueryGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
      } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProjectQueryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
 
			if (st != null) {
                            try {
                                st.close();
                            } catch (SQLException ex) {
                                Logger.getLogger(ProjectQueryGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
			}
 
			if (conn != null) {
                            try {
                                conn.close();
                            } catch (SQLException ex) {
                                Logger.getLogger(ProjectQueryGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
			}
 
      }
        
    }//GEN-LAST:event_editActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Statusp_stat;
    private javax.swing.JTextField _status;
    private javax.swing.JTextField bud;
    private javax.swing.JButton edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel p_budget;
    private javax.swing.JTextArea p_desc;
    private javax.swing.JTable pro_tab;
    private javax.swing.JComboBox projectNameJComboBox;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
