package one;
import TableModel.UserModel;
import java.awt.Component;
import java.util.*;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import ooad.User;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jas
 */
public class UserRegistration extends javax.swing.JPanel {

    /**
     * Creates new form UserRegistration
     */
    public static int login = 0;
    public static int user_id;
    CardLayouts cl;
    private Component window;
    
    public UserRegistration() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        g_name = new javax.swing.JLabel();
        u_name = new javax.swing.JTextField();
        g_pwd = new javax.swing.JLabel();
        u_pwd = new javax.swing.JPasswordField();
        u_login = new javax.swing.JButton();

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        topPanel.setSize(new java.awt.Dimension(600, 600));

        g_name.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        g_name.setText("User Name: ");

        u_name.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        u_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        g_pwd.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        g_pwd.setText("Password: ");

        u_pwd.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        u_pwd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        u_login.setBackground(new java.awt.Color(255, 51, 102));
        u_login.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        u_login.setText("Login");
        u_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(g_name)
                            .addComponent(g_pwd))
                        .addGap(18, 18, 18)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(u_pwd, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(u_name)))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(u_login)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g_name)
                    .addComponent(u_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g_pwd)
                    .addComponent(u_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(u_login)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void u_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_loginActionPerformed
        // TODO add your handling code here:
        String user_name = u_name.getText();
        String password = u_pwd.getText();
        
        UserModel user = new UserModel();
        cl = new CardLayouts();
        
        for(User item : user.userResultList){
            Component frame = null;
            
            if(item.getUserName().equals(user_name) && item.getPassword().equals(password)){
                user_id = item.getUserId();
                if(item.getUserName().equals("admin"))
                    login = 1;
                JOptionPane.showMessageDialog(window, "Login successful","Message Dialog", JOptionPane.PLAIN_MESSAGE);
                cl.display();
            }
            
            
            
         
            
        } 
        
    }//GEN-LAST:event_u_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel g_name;
    private javax.swing.JLabel g_pwd;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton u_login;
    private javax.swing.JTextField u_name;
    private javax.swing.JPasswordField u_pwd;
    // End of variables declaration//GEN-END:variables
}
